CPU = cortex-m7

DEV_TYPE = STM32f7xx
BOARD_INC = $(BOARD_PATH) $(TUSB_PATH)/Drivers/$(DEV_TYPE)_HAL_Driver/Inc $(TUSB_PATH)/Drivers/CMSIS/Device/ST/$(DEV_TYPE)/Include
BOARD_DEF = USE_HAL_DRIVER STM32F767xx HSE_VALUE=8000000
BOARD_SRC = $(BOARD_PATH)/system_stm32f7xx.c
BOARD_SRC += $(TUSB_PATH)/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f767xx.s
LDSCRIPT = $(BOARD_PATH)/STM32F767ZITx_FLASH.ld

