CPU = cortex-m4

DEV_TYPE = STM32f3xx
BOARD_INC = $(BOARD_PATH) $(TUSB_PATH)/Drivers/$(DEV_TYPE)_HAL_Driver/Inc $(TUSB_PATH)/Drivers/CMSIS/Device/ST/$(DEV_TYPE)/Include
BOARD_DEF = USE_HAL_DRIVER STM32F303xC HSE_VALUE=8000000
BOARD_SRC = $(BOARD_PATH)/system_stm32f3xx.c
BOARD_SRC += $(TUSB_PATH)/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.s
LDSCRIPT = $(BOARD_PATH)/STM32F303VCTx_FLASH.ld

